os:
- linux
services:
- docker
language: node_js
node_js:
- 6.11.3
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add @angular/cli
install:
- cd my-app/
- yarn install
script:
- ng serve --sourcemap=false &
- sleep 10
- curl -v http://localhost:4200/
before_deploy:
- ng build --prod --aot
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: formation-angular